### PR TITLE
Change forking_workflow_exercise_url to repo.

### PR DESCRIPTION
**Pull request by blindij**

### CODE REVIEW

**Comment by bast** [comment]
I think the idea of this was more that this could be customized on a fork. Unless you want to change the actual template but then you can send a PR to that one. Or did I misunderstand?

**Comment by blindij** [comment]
The link in Part A (Fork and clone) points to nowhere, https://github.com/coderefinery/forking-workflow-exercise. Should it not point to the a actual repository used during the lesson?

**Comment by blindij** [comment]
Now I get  it. I fork the git-collaborative, and make the lesson point to my fork. Right.

**Comment by bast** [comment]
> The link in Part A (Fork and clone) points to nowhere, https://github.com/coderefinery/forking-workflow-exercise. Should it not point to the a actual repository used during the lesson?

Because the exercise repo has not been set up yet.

We have a couple of possibilities:
- fork lesson, adjust exercise link
- keep lesson, adjust exercise link
- keep lesson, keep exercise link, but change exercise

So the "right" solution "depends" on what is the goal.

Option 1 has most flexibility but requires a follow-up after the course to get the changes into the main line if this is the goal.

**Pull request closed without merging**
