### PR TITLE
Update the instructor guide

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by bast** [comment]
Once #64 is in, I will use the variables in the guide to make it less confusing.

**Comment by wikfeldt** [comment]
oops, i accidentally "marked this pull request as ready for review", sowwy.
The changes look good to me

**Comment by wikfeldt** [comment]
i guess now when #64 is merged it's safe to merge this one

**Comment by bast** [comment]
No problem at all - thanks for reviewing the PRs!

**Pull request merged**
