### PR TITLE
Lesson update

### PR DESCRIPTION
**Pull request by bast**
This is work in progress so a merge is not expected yet. But you can either follow of what I do, or you can also give feedback and suggestion and criticize changes. I will mark when it's ready to be merged but please do comment on changes.

### CODE REVIEW

**Comment by bast** [comment]
Two changes are ahead:
- forking workflow will create a feature branch always, we train participants from day 0 to not commit to main line
- cloning, pushing, fetching, pulling is done in a collaborative exercise instead of a dry lecture: we add participants as collaborators and let them do the steps so that they see rejected pushes and merge commits on their computers, then we discuss them

**Comment by bast** [comment]
Remains to be done: first part (cloning, pushing, fetching, pulling) to be turned into a collaborative exercise. I will do this tomorrow.

**Comment by wikfeldt** [comment]
i think this looks great. But as you mention, there needs to be some sort of exercise in the first episode, to warm everyone up for the massive exercise on forking-pull requests

**Comment by bast** [comment]
Thanks for feedback. I will today exercisify the first part. We will start with clone, then push, it will work only for one person, then we discuss the rejected push, then fetch/pull, then merge commits.

**Comment by bast** [comment]
Drafting the exercise: https://github.com/coderefinery/centralized-workflow-exercise

**Comment by bast** [comment]
Ready to go from my perspective.

**Pull request merged**
